version: "3.9"

services:
  website:
    image: nginx:alpine
    container_name: homelab-website
    volumes:
      - .:/usr/share/nginx/html:ro 
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - homelab-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  homelab-net:
    external: true    # Use the existing network from main compose file