version: "3.9"

services:
  website:
    image: nginx:alpine
    container_name: homelab-website
    volumes:
      - ./website:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    networks:
      - homelab-net
    restart: unless-stopped
    labels:
      caddy.expose: "true"
      caddy.root: "true"          # this service becomes the root site
      caddy.host_port: "8080"     # host-side port (left side of HOST:CONTAINER)

networks:
  homelab-net:
    external: true
